volumes:
  pg_bank_rest:

services:
  bank_rest_db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Bank_REST
    volumes:
      - pg_bank_rest:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - bank_rest_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://bank_rest_db:5432/Bank_REST'
      JAVA_OPTS: '-Xmx512m'
